-- CLIENTES
CREATE GENERATOR GEN_CLIENTE_ID;

CREATE TABLE CLIENTE (
    ID            INTEGER NOT NULL,
    NOME          VARCHAR(120) NOT NULL,
    DOCUMENTO     VARCHAR(20),
    EMAIL         VARCHAR(120),
    TELEFONE      VARCHAR(30),
    DATACADASTRO  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID);

CREATE OR ALTER TRIGGER CLIENTE_BI FOR CLIENTE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CLIENTE_ID,1);
END;

GRANT USAGE ON SEQUENCE GEN_CLIENTE_ID TO SYSDBA WITH GRANT OPTION;

-- ORDEM_SERVICO
CREATE GENERATOR GEN_ORDEM_SERVICO_ID;

CREATE TABLE ORDEM_SERVICO (
    ID                  INTEGER NOT NULL,
    CLIENTE_ID          INTEGER NOT NULL,
    DATA_ABERTURA       DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_PREVISTA       DATE,
    DATA_FECHAMENTO     DATE,
    STATUS              VARCHAR(15) NOT NULL,
    DESCRICAO_PROBLEMA  VARCHAR(500),
    VALOR_TOTAL         NUMERIC(15,2) DEFAULT 0
);

ALTER TABLE ORDEM_SERVICO ADD CONSTRAINT PK_ORDEM_SERVICO PRIMARY KEY (ID);

CREATE INDEX IDX_OS_CLIENTE ON ORDEM_SERVICO (CLIENTE_ID);
CREATE INDEX IDX_OS_DATA_ABERTURA ON ORDEM_SERVICO (DATA_ABERTURA);
CREATE INDEX IDX_OS_FECHAMENTO ON ORDEM_SERVICO (DATA_FECHAMENTO);
CREATE INDEX IDX_OS_PREVISTA ON ORDEM_SERVICO (DATA_PREVISTA);
CREATE INDEX IDX_OS_STATUS ON ORDEM_SERVICO (STATUS);

CREATE OR ALTER TRIGGER ORDEM_SERVICO_BI FOR ORDEM_SERVICO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ORDEM_SERVICO_ID,1);
END;

-- ITEM_ORDEM
CREATE GENERATOR GEN_ITEM_ORDEM_ID;

CREATE TABLE ITEM_ORDEM (
    ID              INTEGER NOT NULL,
    ORDEM_ID        INTEGER NOT NULL,
    DESCRICAO       VARCHAR(200) NOT NULL,
    QUANTIDADE      NUMERIC(12,2) NOT NULL,
    VALOR_UNITARIO  NUMERIC(15,2) NOT NULL
);

ALTER TABLE ITEM_ORDEM ADD CONSTRAINT PK_ITEM_ORDEM PRIMARY KEY (ID);

ALTER TABLE ITEM_ORDEM ADD CONSTRAINT FK_ITEM_ORDEM FOREIGN KEY (ORDEM_ID) REFERENCES ORDEM_SERVICO (ID) ON UPDATE CASCADE;

CREATE OR ALTER TRIGGER ITEM_ORDEM_BI FOR ITEM_ORDEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ITEM_ORDEM_ID,1);
END;

GRANT USAGE ON SEQUENCE GEN_ITEM_ORDEM_ID TO SYSDBA WITH GRANT OPTION;